export const INDIAN_STATES = [
  { label: 'Andhra Pradesh', value: 'AP' },
  { label: 'Arunachal Pradesh', value: 'AR' },
  { label: 'Assam', value: 'AS' },
  { label: 'Bihar', value: 'BR' },
  { label: 'Chhattisgarh', value: 'CG' },
  { label: 'Goa', value: 'GA' },
  { label: 'Gujarat', value: 'GJ' },
  { label: 'Haryana', value: 'HR' },
  { label: 'Himachal Pradesh', value: 'HP' },
  { label: 'Jharkhand', value: 'JH' },
  { label: 'Karnataka', value: 'KA' },
  { label: 'Kerala', value: 'KL' },
  { label: 'Madhya Pradesh', value: 'MP' },
  { label: 'Maharashtra', value: 'MH' },
  { label: 'Manipur', value: 'MN' },
  { label: 'Meghalaya', value: 'ML' },
  { label: 'Mizoram', value: 'MZ' },
  { label: 'Nagaland', value: 'NL' },
  { label: 'Odisha', value: 'OD' },
  { label: 'Punjab', value: 'PB' },
  { label: 'Rajasthan', value: 'RJ' },
  { label: 'Sikkim', value: 'SK' },
  { label: 'Tamil Nadu', value: 'TN' },
  { label: 'Telangana', value: 'TS' },
  { label: 'Tripura', value: 'TR' },
  { label: 'Uttar Pradesh', value: 'UP' },
  { label: 'Uttarakhand', value: 'UK' },
  { label: 'West Bengal', value: 'WB' },
  { label: 'Andaman and Nicobar Islands', value: 'AN' },
  { label: 'Chandigarh', value: 'CH' },
  { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'DN' },
  { label: 'Delhi', value: 'DL' },
  { label: 'Jammu and Kashmir', value: 'JK' },
  { label: 'Ladakh', value: 'LA' },
  { label: 'Lakshadweep', value: 'LD' },
  { label: 'Puducherry', value: 'PY' },
  { label: 'All India', value: 'AI' },
]

export const EDUCATION_LEVELS = [
  { label: '8th Pass', value: '8TH' },
  { label: '10th Pass', value: '10TH' },
  { label: '12th Pass', value: '12TH' },
  { label: 'ITI', value: 'ITI' },
  { label: 'Diploma', value: 'Diploma' },
  { label: 'Graduate', value: 'Graduate' },
  { label: 'Post Graduate', value: 'PG' },
  { label: 'PhD', value: 'PhD' },
  { label: 'B.Tech/B.E', value: 'B.Tech' },
  { label: 'M.Tech/M.E', value: 'M.Tech' },
  { label: 'MBBS', value: 'MBBS' },
  { label: 'BDS', value: 'BDS' },
  { label: 'CA/ICWA', value: 'CA_ICWA' },
  { label: 'LLB', value: 'LLB' },
  { label: 'LLM', value: 'LLM' },
  { label: 'B.Ed', value: 'B.Ed' },
  { label: 'M.Ed', value: 'M.Ed' },
  { label: 'B.Pharm', value: 'B.Pharm' },
  { label: 'M.Pharm', value: 'M.Pharm' },
  { label: 'B.Sc Nursing', value: 'B.Sc_Nursing' },
  { label: 'M.Sc Nursing', value: 'M.Sc_Nursing' },
]

export const JOB_CATEGORIES = [
  { label: 'Bank', value: 'bank' },
  { label: 'Teaching', value: 'teaching' },
  { label: 'Engineering', value: 'engineering' },
  { label: 'Railway', value: 'railway' },
  { label: 'Police/Defence', value: 'police' },
  { label: 'SSC', value: 'ssc' },
  { label: 'UPSC', value: 'upsc' },
  { label: 'State PSC', value: 'state_psc' },
  { label: 'PSU', value: 'psu' },
  { label: 'Judiciary', value: 'judiciary' },
  { label: 'Medical/Healthcare', value: 'medical' },
  { label: 'Research/Scientist', value: 'research' },
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'Sports Quota', value: 'sports' },
  { label: 'Other', value: 'other' },
]
