/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    jobs: Job;
    'saved-jobs': SavedJob;
    'job-applications': JobApplication;
    broadcasts: Broadcast;
    posts: Post;
    categories: Category;
    'email-logs': EmailLog;
    'mock-tests': MockTest;
    questions: Question;
    'test-attempts': TestAttempt;
    'previous-papers': PreviousPaper;
    comments: Comment;
    'practice-topics': PracticeTopic;
    'current-affairs': CurrentAffair;
    syllabus: Syllabus;
    threads: Thread;
    'forum-topics': ForumTopic;
    votes: Vote;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'saved-jobs': SavedJobsSelect<false> | SavedJobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    broadcasts: BroadcastsSelect<false> | BroadcastsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    'mock-tests': MockTestsSelect<false> | MockTestsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'test-attempts': TestAttemptsSelect<false> | TestAttemptsSelect<true>;
    'previous-papers': PreviousPapersSelect<false> | PreviousPapersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'practice-topics': PracticeTopicsSelect<false> | PracticeTopicsSelect<true>;
    'current-affairs': CurrentAffairsSelect<false> | CurrentAffairsSelect<true>;
    syllabus: SyllabusSelect<false> | SyllabusSelect<true>;
    threads: ThreadsSelect<false> | ThreadsSelect<true>;
    'forum-topics': ForumTopicsSelect<false> | ForumTopicsSelect<true>;
    votes: VotesSelect<false> | VotesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
    seoSettings: SeoSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seoSettings: SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('superadmin' | 'admin' | 'candidate')[];
  /**
   * Add your educational qualifications from 10th onwards
   */
  educationHistory?:
    | {
        level: '10th' | '12th' | 'Diploma' | 'Graduate' | 'PostGraduate' | 'PhD';
        degree?: string | null;
        stream?: string | null;
        passingYear?: number | null;
        percentage?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * DEPRECATED: Use Education History above. (Read-only)
   */
  qualification?:
    | (
        | '8TH'
        | '10TH'
        | '12TH'
        | 'ITI'
        | 'Diploma'
        | 'Graduate'
        | 'PG'
        | 'PhD'
        | 'B.Tech'
        | 'M.Tech'
        | 'MBBS'
        | 'BDS'
        | 'CA_ICWA'
        | 'LLB'
        | 'LLM'
        | 'B.Ed'
        | 'M.Ed'
        | 'B.Pharm'
        | 'M.Pharm'
        | 'B.Sc_Nursing'
        | 'M.Sc_Nursing'
      )[]
    | null;
  /**
   * Your home state (for domicile-based jobs)
   */
  domicileState?:
    | (
        | 'AP'
        | 'AR'
        | 'AS'
        | 'BR'
        | 'CG'
        | 'GA'
        | 'GJ'
        | 'HR'
        | 'HP'
        | 'JH'
        | 'KA'
        | 'KL'
        | 'MP'
        | 'MH'
        | 'MN'
        | 'ML'
        | 'MZ'
        | 'NL'
        | 'OD'
        | 'PB'
        | 'RJ'
        | 'SK'
        | 'TN'
        | 'TS'
        | 'TR'
        | 'UP'
        | 'UK'
        | 'WB'
        | 'AN'
        | 'CH'
        | 'DN'
        | 'DL'
        | 'JK'
        | 'LA'
        | 'LD'
        | 'PY'
        | 'AI'
      )
    | null;
  /**
   * States where you want to find jobs
   */
  preferredStates?:
    | (
        | 'AP'
        | 'AR'
        | 'AS'
        | 'BR'
        | 'CG'
        | 'GA'
        | 'GJ'
        | 'HR'
        | 'HP'
        | 'JH'
        | 'KA'
        | 'KL'
        | 'MP'
        | 'MH'
        | 'MN'
        | 'ML'
        | 'MZ'
        | 'NL'
        | 'OD'
        | 'PB'
        | 'RJ'
        | 'SK'
        | 'TN'
        | 'TS'
        | 'TR'
        | 'UP'
        | 'UK'
        | 'WB'
        | 'AN'
        | 'CH'
        | 'DN'
        | 'DL'
        | 'JK'
        | 'LA'
        | 'LD'
        | 'PY'
        | 'AI'
      )[]
    | null;
  /**
   * Used to calculate age eligibility
   */
  dateOfBirth?: string | null;
  /**
   * Reservation category (for age relaxation)
   */
  category?: ('General' | 'OBC' | 'SC' | 'ST' | 'EWS') | null;
  gender?: ('Male' | 'Female' | 'Other') | null;
  disability?: {
    isEnabled?: boolean | null;
    type?: ('VI' | 'HI' | 'LD' | 'Other') | null;
    percentage?: number | null;
  };
  stats?: {
    /**
     * Last time the user logged in
     */
    lastLoginAt?: string | null;
    /**
     * Total number of logins
     */
    loginCount?: number | null;
    /**
     * Total applications submitted (auto-calculated)
     */
    applicationCount?: number | null;
  };
  notificationPreferences?: {
    emailAlerts?: boolean | null;
    /**
     * Summary of new jobs every morning
     */
    dailyDigest?: boolean | null;
    /**
     * Immediate email when a high-match job is posted
     */
    instantJobAlerts?: boolean | null;
    /**
     * Alerts for Admit Card/Result of applied jobs
     */
    applicationUpdates?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  postDate: string;
  recruitmentBoard: string;
  postName: string;
  advtNo?: string | null;
  totalVacancies?: number | null;
  lastDate: string;
  status?: ('open' | 'admit_card' | 'result' | 'answer_key' | 'syllabus' | 'edu_notification' | 'closed') | null;
  category?:
    | (
        | 'bank'
        | 'teaching'
        | 'engineering'
        | 'railway'
        | 'police'
        | 'ssc'
        | 'upsc'
        | 'state_psc'
        | 'psu'
        | 'judiciary'
        | 'medical'
        | 'research'
        | 'agriculture'
        | 'sports'
        | 'other'
      )[]
    | null;
  state?:
    | (
        | 'AP'
        | 'AR'
        | 'AS'
        | 'BR'
        | 'CG'
        | 'GA'
        | 'GJ'
        | 'HR'
        | 'HP'
        | 'JH'
        | 'KA'
        | 'KL'
        | 'MP'
        | 'MH'
        | 'MN'
        | 'ML'
        | 'MZ'
        | 'NL'
        | 'OD'
        | 'PB'
        | 'RJ'
        | 'SK'
        | 'TN'
        | 'TS'
        | 'TR'
        | 'UP'
        | 'UK'
        | 'WB'
        | 'AN'
        | 'CH'
        | 'DN'
        | 'DL'
        | 'JK'
        | 'LA'
        | 'LD'
        | 'PY'
        | 'AI'
      )
    | null;
  education?:
    | (
        | '8TH'
        | '10TH'
        | '12TH'
        | 'ITI'
        | 'Diploma'
        | 'Graduate'
        | 'PG'
        | 'PhD'
        | 'B.Tech'
        | 'M.Tech'
        | 'MBBS'
        | 'BDS'
        | 'CA_ICWA'
        | 'LLB'
        | 'LLM'
        | 'B.Ed'
        | 'M.Ed'
        | 'B.Pharm'
        | 'M.Pharm'
        | 'B.Sc_Nursing'
        | 'M.Sc_Nursing'
      )[]
    | null;
  /**
   * When applications open (if different from post date)
   */
  applicationStartDate?: string | null;
  /**
   * Scheduled exam/test date
   */
  examDate?: string | null;
  /**
   * When admit cards will be released
   */
  admitCardDate?: string | null;
  /**
   * Expected result declaration date
   */
  resultDate?: string | null;
  /**
   * Reference date for age calculation (e.g., "as on 01-08-2025")
   */
  ageCalculationDate?: string | null;
  structuredRequirements?: {
    education?:
      | {
          levels?: ('10th' | '12th' | 'Diploma' | 'Graduate' | 'PostGraduate')[] | null;
          degrees?: string[] | null;
          streams?: string[] | null;
          id?: string | null;
        }[]
      | null;
    experience?: {
      minYears?: number | null;
      maxYears?: number | null;
      mandatorySkills?: string[] | null;
    };
    gender?: ('Male' | 'Female' | 'Any') | null;
  };
  /**
   * Minimum age requirement in years
   */
  minimumAge?: number | null;
  /**
   * Maximum age requirement in years
   */
  maximumAge?: number | null;
  ageRelaxationRules?:
    | {
        category: 'SC' | 'ST' | 'OBC' | 'PWD' | 'EWS' | 'Ex-Serviceman';
        years: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Age relaxation explanation details
   */
  ageRelaxation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Height, weight, chest, and other physical requirements
   */
  physicalStandards?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Application fee for General/UR category (e.g., "Rs. 159/-")
   */
  feeGeneral?: string | null;
  /**
   * Application fee for OBC category
   */
  feeOBC?: string | null;
  /**
   * Application fee for SC category
   */
  feeSC?: string | null;
  /**
   * Application fee for ST category
   */
  feeST?: string | null;
  /**
   * List exemptions (e.g., "Female, PWD, Ex-servicemen")
   */
  feeExemptions?: string | null;
  /**
   * Accepted payment methods (e.g., "Online via Credit Card, Debit Card, Net Banking")
   */
  paymentModes?: string | null;
  /**
   * Detailed category/post/gender-wise vacancy breakdown table
   */
  vacancyBreakdown?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * SC/ST/OBC/EWS reservation information
   */
  reservationDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Step-by-step application instructions
   */
  applicationProcess?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * List of documents required for application
   */
  requiredDocuments?:
    | {
        /**
         * Name of the document (e.g., "10th Marksheet")
         */
        documentName: string;
        /**
         * Additional details about the document
         */
        description?: string | null;
        /**
         * Is this document mandatory?
         */
        mandatory?: boolean | null;
        id?: string | null;
      }[]
    | null;
  applicationFee?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  selectionProcess?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  importantLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  shortNotification?: (number | null) | Media;
  previousPapers?: (number | PreviousPaper)[] | null;
  /**
   * Expected cutoff marks (out of 100) for qualification prediction engine
   */
  expectedCutoff?: number | null;
  aiSummary?: string | null;
  eligibilityDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  salaryStipend?: string | null;
  applyLink?: string | null;
  officialNotification?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "previous-papers".
 */
export interface PreviousPaper {
  id: number;
  title: string;
  examName: string;
  examCategory: 'ssc' | 'banking' | 'teaching' | 'upsc' | 'defence' | 'state';
  year: number;
  file: number | Media;
  downloadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs".
 */
export interface SavedJob {
  id: number;
  user: number | User;
  job: number | Job;
  /**
   * Personal notes about this job
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  user: number | User;
  job: number | Job;
  status: 'applied' | 'admit-card-downloaded' | 'exam-given' | 'result-awaited' | 'selected' | 'rejected';
  /**
   * Date when you applied
   */
  applicationDate: string;
  /**
   * Date when admit card was downloaded
   */
  admitCardDate?: string | null;
  /**
   * Exam date
   */
  examDate?: string | null;
  /**
   * Result declaration date
   */
  resultDate?: string | null;
  /**
   * Application notes, preparation status, etc.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send bulk emails to users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts".
 */
export interface Broadcast {
  id: number;
  subject: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Who should receive this email?
   */
  targetAudience: 'all' | 'subscribers';
  status: 'draft' | 'sent';
  sentAt?: string | null;
  /**
   * Number of users emailed
   */
  recipientCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  type: 'sent' | 'delivered' | 'open' | 'click' | 'bounce' | 'complaint';
  email: string;
  resendId?: string | null;
  campaign?: string | null;
  linkClicked?: string | null;
  user?: (number | null) | User;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mock-tests".
 */
export interface MockTest {
  id: number;
  title: string;
  examType: 'ibps' | 'ssc' | 'rrb' | 'upsc' | 'state';
  duration: number;
  hasSectionalTimer?: boolean | null;
  sections?:
    | {
        name: string;
        /**
         * Required if Sectional Timing is enabled
         */
        duration?: number | null;
        order: number;
        subject?: ('quant' | 'reasoning' | 'english' | 'ga' | 'computer') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select questions for this test
   */
  questions?: (number | Question)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  options: {
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    isCorrect: boolean;
    id?: string | null;
  }[];
  explanation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  marks: number;
  negativeMarks: number;
  topic?: (number | PracticeTopic)[] | null;
  subject: 'quant' | 'reasoning' | 'english' | 'ga' | 'computer';
  difficulty?: ('easy' | 'medium' | 'hard') | null;
  /**
   * Tag this question for specific exam types (optional)
   */
  examTags?: ('bank' | 'ssc' | 'railway' | 'upsc' | 'defense' | 'engineering')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-topics".
 */
export interface PracticeTopic {
  id: number;
  name: string;
  /**
   * URL-friendly name (e.g., problems-on-trains)
   */
  slug?: string | null;
  parent?: (number | null) | PracticeTopic;
  category:
    | 'General Aptitude'
    | 'Verbal and Reasoning'
    | 'Current Affairs & GK'
    | 'Engineering'
    | 'Programming'
    | 'Technical MCQs'
    | 'Medical Science'
    | 'Puzzles';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-attempts".
 */
export interface TestAttempt {
  id: number;
  user: number | User;
  test: number | MockTest;
  status?: ('in_progress' | 'completed') | null;
  score?: number | null;
  totalTimeSpent?: number | null;
  answers?:
    | {
        question: number | Question;
        userSelectedOptionId?: string | null;
        status?: ('answered' | 'marked_review' | 'ans_marked_review' | 'skipped' | 'not_visited') | null;
        timeSpent?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  user: number | User;
  question?: (number | null) | Question;
  thread?: (number | null) | Thread;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'published' | 'pending' | 'rejected';
  upvotes?: number | null;
  downvotes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads".
 */
export interface Thread {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  relatedQuestion?: (number | null) | Question;
  topic?: (number | null) | ForumTopic;
  upvotes?: number | null;
  downvotes?: number | null;
  tags?: ('general' | 'strategy' | 'doubt' | 'news' | 'success-story')[] | null;
  status: 'published' | 'pending' | 'rejected';
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-topics".
 */
export interface ForumTopic {
  id: number;
  title: string;
  description?: string | null;
  icon?: (number | null) | Media;
  slug?: string | null;
  threadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "current-affairs".
 */
export interface CurrentAffair {
  id: number;
  title: string;
  date: string;
  category: 'national' | 'international' | 'sports' | 'economy' | 'science-tech' | 'appointments' | 'awards';
  summary: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  source?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabus".
 */
export interface Syllabus {
  id: number;
  title: string;
  category: 'ssc' | 'banking' | 'upsc' | 'railways' | 'teaching' | 'state-exams' | 'defence';
  subject?: string | null;
  topics?:
    | {
        topicName: string;
        subTopics?: string | null;
        weightage?: string | null;
        id?: string | null;
      }[]
    | null;
  pdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes".
 */
export interface Vote {
  id: number;
  user: number | User;
  type: 'up' | 'down';
  thread?: (number | null) | Thread;
  comment?: (number | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'jobs';
          value: number | Job;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'jobs';
        value: number | Job;
      }
    | {
        relationTo: 'posts';
        value: number | Post;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'saved-jobs';
        value: number | SavedJob;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'broadcasts';
        value: number | Broadcast;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'mock-tests';
        value: number | MockTest;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'test-attempts';
        value: number | TestAttempt;
      } | null)
    | ({
        relationTo: 'previous-papers';
        value: number | PreviousPaper;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'practice-topics';
        value: number | PracticeTopic;
      } | null)
    | ({
        relationTo: 'current-affairs';
        value: number | CurrentAffair;
      } | null)
    | ({
        relationTo: 'syllabus';
        value: number | Syllabus;
      } | null)
    | ({
        relationTo: 'threads';
        value: number | Thread;
      } | null)
    | ({
        relationTo: 'forum-topics';
        value: number | ForumTopic;
      } | null)
    | ({
        relationTo: 'votes';
        value: number | Vote;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  educationHistory?:
    | T
    | {
        level?: T;
        degree?: T;
        stream?: T;
        passingYear?: T;
        percentage?: T;
        id?: T;
      };
  qualification?: T;
  domicileState?: T;
  preferredStates?: T;
  dateOfBirth?: T;
  category?: T;
  gender?: T;
  disability?:
    | T
    | {
        isEnabled?: T;
        type?: T;
        percentage?: T;
      };
  stats?:
    | T
    | {
        lastLoginAt?: T;
        loginCount?: T;
        applicationCount?: T;
      };
  notificationPreferences?:
    | T
    | {
        emailAlerts?: T;
        dailyDigest?: T;
        instantJobAlerts?: T;
        applicationUpdates?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  postDate?: T;
  recruitmentBoard?: T;
  postName?: T;
  advtNo?: T;
  totalVacancies?: T;
  lastDate?: T;
  status?: T;
  category?: T;
  state?: T;
  education?: T;
  applicationStartDate?: T;
  examDate?: T;
  admitCardDate?: T;
  resultDate?: T;
  ageCalculationDate?: T;
  structuredRequirements?:
    | T
    | {
        education?:
          | T
          | {
              levels?: T;
              degrees?: T;
              streams?: T;
              id?: T;
            };
        experience?:
          | T
          | {
              minYears?: T;
              maxYears?: T;
              mandatorySkills?: T;
            };
        gender?: T;
      };
  minimumAge?: T;
  maximumAge?: T;
  ageRelaxationRules?:
    | T
    | {
        category?: T;
        years?: T;
        id?: T;
      };
  ageRelaxation?: T;
  physicalStandards?: T;
  feeGeneral?: T;
  feeOBC?: T;
  feeSC?: T;
  feeST?: T;
  feeExemptions?: T;
  paymentModes?: T;
  vacancyBreakdown?: T;
  reservationDetails?: T;
  applicationProcess?: T;
  requiredDocuments?:
    | T
    | {
        documentName?: T;
        description?: T;
        mandatory?: T;
        id?: T;
      };
  applicationFee?: T;
  selectionProcess?: T;
  importantLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  shortNotification?: T;
  previousPapers?: T;
  expectedCutoff?: T;
  aiSummary?: T;
  eligibilityDetails?: T;
  salaryStipend?: T;
  applyLink?: T;
  officialNotification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs_select".
 */
export interface SavedJobsSelect<T extends boolean = true> {
  user?: T;
  job?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  user?: T;
  job?: T;
  status?: T;
  applicationDate?: T;
  admitCardDate?: T;
  examDate?: T;
  resultDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "broadcasts_select".
 */
export interface BroadcastsSelect<T extends boolean = true> {
  subject?: T;
  content?: T;
  targetAudience?: T;
  status?: T;
  sentAt?: T;
  recipientCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  type?: T;
  email?: T;
  resendId?: T;
  campaign?: T;
  linkClicked?: T;
  user?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mock-tests_select".
 */
export interface MockTestsSelect<T extends boolean = true> {
  title?: T;
  examType?: T;
  duration?: T;
  hasSectionalTimer?: T;
  sections?:
    | T
    | {
        name?: T;
        duration?: T;
        order?: T;
        subject?: T;
        id?: T;
      };
  questions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  text?: T;
  options?:
    | T
    | {
        text?: T;
        isCorrect?: T;
        id?: T;
      };
  explanation?: T;
  marks?: T;
  negativeMarks?: T;
  topic?: T;
  subject?: T;
  difficulty?: T;
  examTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-attempts_select".
 */
export interface TestAttemptsSelect<T extends boolean = true> {
  user?: T;
  test?: T;
  status?: T;
  score?: T;
  totalTimeSpent?: T;
  answers?:
    | T
    | {
        question?: T;
        userSelectedOptionId?: T;
        status?: T;
        timeSpent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "previous-papers_select".
 */
export interface PreviousPapersSelect<T extends boolean = true> {
  title?: T;
  examName?: T;
  examCategory?: T;
  year?: T;
  file?: T;
  downloadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  user?: T;
  question?: T;
  thread?: T;
  content?: T;
  status?: T;
  upvotes?: T;
  downvotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-topics_select".
 */
export interface PracticeTopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "current-affairs_select".
 */
export interface CurrentAffairsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  category?: T;
  summary?: T;
  content?: T;
  source?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabus_select".
 */
export interface SyllabusSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  subject?: T;
  topics?:
    | T
    | {
        topicName?: T;
        subTopics?: T;
        weightage?: T;
        id?: T;
      };
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "threads_select".
 */
export interface ThreadsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  relatedQuestion?: T;
  topic?: T;
  upvotes?: T;
  downvotes?: T;
  tags?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-topics_select".
 */
export interface ForumTopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  slug?: T;
  threadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes_select".
 */
export interface VotesSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  thread?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'jobs';
                value: number | Job;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  telegramLink?: string | null;
  whatsappLink?: string | null;
  twitterLink?: string | null;
  facebookLink?: string | null;
  instagramLink?: string | null;
  youtubeLink?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  enableEmailSystem?: boolean | null;
  fromName: string;
  fromEmail: string;
  /**
   * Email to receive system health alerts or new signup notifications
   */
  adminAlertEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoSettings".
 */
export interface SeoSetting {
  id: number;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  defaultOGImage?: (number | null) | Media;
  /**
   * Comma-separated keywords
   */
  keywords?: string | null;
  /**
   * e.g., @aijobalert
   */
  twitterHandle?: string | null;
  facebookAppId?: string | null;
  /**
   * e.g., G-XXXXXXXXXX
   */
  googleAnalyticsId?: string | null;
  googleSiteVerification?: string | null;
  googleAdsenseId?: string | null;
  jobsSEO?: {
    /**
     * Use {postName}, {organization}, {lastDate}
     */
    titleTemplate?: string | null;
    descriptionTemplate?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  telegramLink?: T;
  whatsappLink?: T;
  twitterLink?: T;
  facebookLink?: T;
  instagramLink?: T;
  youtubeLink?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  enableEmailSystem?: T;
  fromName?: T;
  fromEmail?: T;
  adminAlertEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoSettings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  defaultOGImage?: T;
  keywords?: T;
  twitterHandle?: T;
  facebookAppId?: T;
  googleAnalyticsId?: T;
  googleSiteVerification?: T;
  googleAdsenseId?: T;
  jobsSEO?:
    | T
    | {
        titleTemplate?: T;
        descriptionTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}